name: Build & Push to Docker Hub

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  DOCKERHUB_USERNAME: banasa44
  IMAGE_NAME: comfyui

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - { file: Dockerfiles/Dockerfile.4090, tag: 4090, build_args: '' }
          - { file: Dockerfiles/Dockerfile.5090, tag: 5090, build_args: '' }
          - {
              file: Dockerfiles/Dockerfile.5090,
              tag: 5090-cu126,
              build_args: 'TORCH_INDEX_URL=https://download.pytorch.org/whl/cu126',
            }
    steps:
      - uses: actions/checkout@v4

      - name: Maximize runner disk space
        run: |
          sudo rm -rf /usr/local/lib/android || true
          sudo rm -rf /opt/ghc || true
          sudo rm -rf /usr/share/dotnet || true
          docker system prune -af || true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.target.file }}
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ matrix.target.tag }}
          build-args: ${{ matrix.target.build_args }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
