name: Build & Push to Docker Hub

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  DOCKERHUB_USERNAME: banasa44
  IMAGE_NAME: comfyui

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - { file: Dockerfiles/Dockerfile.4090, tag: 4090 }
          - { file: Dockerfiles/Dockerfile.5090, tag: 5090 }
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.target.file }}
          push: true
          tags: |
            banasa44/comfyui:${{ matrix.target.tag }}
